# Location: config/dice.yaml

# Dice Simulation Configuration
data_generation:
  n_rolls: 1000
  n_dice: 2
  dice_sides: 6
  random_seed: 42

visualization:
  matplotlib:
    figsize: [14, 10]
    title: "Dice Roll Analysis"
    bar_color: "#3498db"
    hist_color: "#e74c3c"
    line_color: "#2ecc71"
    grid: true
    alpha: 0.7

  plotly:
    title: "Interactive Dice Roll Analysis"
    width: 1000
    height: 700
    color_discrete_sequence: ["#3498db", "#e74c3c", "#2ecc71", "#f39c12"]
    template: "plotly_white"

export:
  filename_prefix: "dice_simulation"
  image_format: "png"
  image_dpi: 300
  html_include_plotlyjs: "cdn"
