# Location: config/github.yaml

# GitHub Statistics Configuration
data_generation:
  n_repositories: 20
  languages:
    [
      "Python",
      "JavaScript",
      "TypeScript",
      "Java",
      "Go",
      "Rust",
      "C++",
      "HTML",
      "CSS",
    ]
  activity_days: 365
  random_seed: 42

  # Repository metrics ranges
  stars_range: [0, 5000]
  forks_range: [0, 1000]
  issues_range: [0, 200]
  commits_range: [1, 2000]

visualization:
  matplotlib:
    figsize: [16, 12]
    title: "GitHub Repository Analytics"
    primary_color: "#24292e"
    secondary_color: "#0366d6"
    success_color: "#28a745"
    warning_color: "#ffd33d"
    danger_color: "#d73a49"
    grid: true
    alpha: 0.8

  plotly:
    title: "Interactive GitHub Dashboard"
    width: 1200
    height: 900
    color_discrete_sequence:
      ["#24292e", "#0366d6", "#28a745", "#ffd33d", "#d73a49", "#6f42c1"]
    template: "plotly_white"

export:
  filename_prefix: "github_analytics"
  image_format: "png"
  image_dpi: 300
  html_include_plotlyjs: "cdn"
