# Location: config/quakes.yaml

# Earthquake Data Configuration
data_generation:
  n_earthquakes: 500
  magnitude_range: [2.0, 8.5]
  depth_range: [1.0, 700.0] # km
  lat_range: [-90, 90]
  lon_range: [-180, 180]
  random_seed: 42

  # Geological hotspots (higher probability regions)
  hotspots:
    - name: "Pacific Ring of Fire"
      lat_center: 35
      lon_center: 140
      lat_range: 30
      lon_range: 50
      probability: 0.4
    - name: "Mid-Atlantic Ridge"
      lat_center: 0
      lon_center: -25
      lat_range: 60
      lon_range: 20
      probability: 0.2

visualization:
  matplotlib:
    figsize: [16, 12]
    title: "Global Earthquake Analysis"
    magnitude_colormap: "plasma"
    depth_colormap: "viridis"
    scatter_alpha: 0.6
    grid: true

  plotly:
    title: "Interactive Global Earthquake Map"
    width: 1200
    height: 800
    mapbox_style: "open-street-map"
    color_continuous_scale: "plasma"
    template: "plotly_white"

export:
  filename_prefix: "earthquake_analysis"
  image_format: "png"
  image_dpi: 300
  html_include_plotlyjs: "cdn"
