# Location: config/weather.yaml

# Weather Data Configuration
data_generation:
  n_days: 365
  base_temperature: 20 # Celsius
  temperature_variation: 15
  seasonal_amplitude: 10
  humidity_base: 60 # Percentage
  humidity_variation: 25
  precipitation_probability: 0.3
  random_seed: 42

visualization:
  matplotlib:
    figsize: [15, 12]
    title: "Weather Patterns Analysis"
    temp_color: "#e74c3c"
    humidity_color: "#3498db"
    precipitation_color: "#9b59b6"
    grid: true
    alpha: 0.8

  plotly:
    title: "Interactive Weather Dashboard"
    width: 1200
    height: 800
    color_discrete_map:
      temperature: "#e74c3c"
      humidity: "#3498db"
      precipitation: "#9b59b6"
    template: "plotly_white"

export:
  filename_prefix: "weather_analysis"
  image_format: "png"
  image_dpi: 300
  html_include_plotlyjs: "cdn"
